### ISSUE TITLE
Main Example Fails

### ISSUE THREAD

**Issue by drasko** [hildjj/node-cbor#23]
Hello,
I just downloaded the module (via `npm`), and tried example from documentation.

It fails:
```
drasko@Lenin:~/cbor/jstest$ node cborTest.js 

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at /home/drasko/cbor/jstest/cborTest.js:8:10
    at Decoder.<anonymous> (/home/drasko/cbor/jstest/node_modules/cbor/lib/decoder.js:119:22)
    at Decoder.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Decoder.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
```

This is the example I am trying:
```
drasko@Lenin:~/cbor/jstest$ cat cborTest.js 
var cbor = require('cbor');
var assert = require('assert');

var encoded = cbor.encode(true); // returns <Buffer f5>
cbor.decodeFirst(encoded, function(error, obj) {
  // error != null if there was an error
  // obj is the unpacked object
  assert.ok(obj[0] === true);
});

// Use integers as keys?
var m = new Map();
m.set(1, 2);
encoded = cbor.encode(m); // <Buffer a1 01 02>
```

**Comment by hildjj** [comment]
README was incorrect.  Updated. `decodeFirst`'s callback returns the first CBOR item, not an array.
