### ISSUE TITLE
TypeError: bignumber is not a constructor, nodejs webpack bundle

### ISSUE THREAD

**Issue by dapplion** [hildjj/node-cbor#88]
In a nodejs app bignumber.js throws in initialization.

```
const MINUS_ONE = new bignumber(-1)
                  ^
TypeError: bignumber is not a constructor
    at Object.<anonymous> (/usr/src/app/server.bundle.js:33351:19)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:24786:16)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.module.exports (/usr/src/app/server.bundle.js:85704:17)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:50098:21)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:48238:12)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
```

bignumber version is 6.0.0, required by:
```
dnp_dappmanager@0.1.0 /path/build/src
└─┬ autobahn@18.3.2
  └─┬ cbor@4.0.0
    └── bignumber.js@6.0.0
```

bignumber is used in a webpack bundle, on node version is LTS 8.12.0, inside a docker container with image node:8.12.0-alpine in an ubuntu server host.

The code referenced by the stack is:
```
function(module, exports, __webpack_require__) {

"use strict";


const bignumber = __webpack_require__(62)
const utils = __webpack_require__(80)
const url = __webpack_require__(63)

const MINUS_ONE = new bignumber(-1)
const TEN = new bignumber(10)
const TWO = new bignumber(2)

/**
 * A CBOR tagged item, where the tag does not have semantics specified at the
 * moment, or those semantics threw an error during parsing. Typically this will
 * be an extension point you're not yet expecting.
 */
class Tagged {

```
Any help and how to fix the issue would be greatly appreciated!

**Comment by hildjj** [comment]
can you put together a small webpack example that would let me recreate this on my own system?  That might help me on #87 anyway.

**Comment by tobowers** [comment]
I'm having this problem using parcel too

**Comment by hildjj** [comment]
Are you bundling bignumber.js (https://github.com/MikeMcl/bignumber.js)?

**Comment by tobowers** [comment]
Thanks for the quick response. I put together a minimal failure case https://github.com/quorumcontrol/minimal-fail-bignumber/tree/master/cbor-bignumber

It does seem unrelated to node-cbor (as ipld has it too). Seems bignumber has been having issues like this: https://github.com/MikeMcl/bignumber.js/issues/166 and https://github.com/MikeMcl/bignumber.js/issues/199

which produces: 
```
+ node dist/index.js
/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:4144
const MINUS_ONE = new bignumber(-1);
                  ^

TypeError: bignumber is not a constructor
    at Object.parcelRequire.1mQP.bignumber.js (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:4144:19)
    at newRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:49:24)
    at localRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:55:14)
    at Object.parcelRequire.b+YO.../vendor/binary-parse-stream (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:4268:16)
    at newRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:49:24)
    at localRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:55:14)
    at Object.parcelRequire.eVKc../utils (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:4921:17)
    at newRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:49:24)
    at localRequire (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:55:14)
    at Object.parcelRequire.dsOm../commented (/Users/tobowers/code/minimal-fail-bignumber/cbor-bignumber/dist/index.js:6434:21)
```

**Comment by hildjj** [comment]
Based on your repro, I *think* that if I change to this it will work in both environments at the moment:

```js
const bignumber = require('bignumber.js').BigNumber
```

**Comment by hildjj** [comment]
Yes, that seemed to work, both in node as well as in the parcel version (after I updated the version number to force whatever cache parcel was using to be refreshed).  I'm going to commit this, and study the CI run carefully.

**Comment by tobowers** [comment]
There is also a change happening at bignumber: https://github.com/parcel-bundler/parcel/issues/2581#issuecomment-457863855

**Comment by hildjj** [comment]
Done.  Look for `cbor@4.1.5`.  Leaving this issue open for now until we decide if this is the final resolution.

**Comment by hildjj** [comment]
Seeing no further comments, let's mark this as done.
